OPENAI_API_KEY="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"
AZURE_ENDPOINT = "https://genai-trigent-openai.openai.azure.com/"
AZURE_API_KEY="51ba5d46601c477b844d3883af93463c"
AZURE_API_VERSION="2024-02-15-preview"
AZURE_DEPLOYMENT_MODEL = "gpt-4o"